describe('Form Submission 3', () => {
  beforeEach(() => {
    cy.visit('https://visitspandau.club/')
  })

  const users = [     
    "Kelly Hunter",
    "Pamela Hernandez",
    "Katherine Andrews",
    "Mary Thompson",
    "Steven Ayers",
    "Morgan Mcmahon",
    "Justin Bradley",
    "Hector Davidson",
    "Aaron Floyd",
    "Thomas Webster",
    "Brandon Gray",
    "Zachary Miller",
    "Margaret Carlson",
    "Christian Holder",
    "Tanya Downs",
    "Robert Quinn",
    "Sherry Martinez",
    "Matthew Dougherty",
    "Timothy Morrow",
    "Gary Ball",
    "Robert Ryan",
    "Courtney Ingram",
    "Andrea Richardson",
    "Morgan Goodman",
    "Tracy Tapia",
    "Cathy Martinez",
    "Beth Perez",
    "Lindsey Thompson",
    "Taylor Whitaker",
    "Sydney Sharp",
    "Lauren Ortiz",
    "Jennifer Mills",
    "Julie Adkins",
    "Carolyn Johnson",
    "Ashley Ingram",
    "Kimberly Foster",
    "Mary Bailey",
    "Joe Coleman",
    "Michael Lane",
    "Justin Wright",
    "George Schultz",
    "Jamie Barnes",
    "James Lewis",
    "Ronald Woods",
    "Nathan Martin",
    "Andrew Duffy",
    "Tiffany David",
    "William Gonzalez Jr.",
    "Christine Park",
    "Mark Brown",
    "Mrs. Veronica Mora PhD",
    "Madeline Gray",
    "John Lucas",
    "Amanda Castro",
    "Courtney Wilson",
    "Mr. Alexander Sanchez",
    "Thomas Bradley",
    "John Villegas",
    "Emily Watts",
    "Wyatt Hudson",
    "Kari Dyer",
    "Alyssa Mills",
    "Nathan Daniels",
    "Michelle Humphrey",
    "Nancy Thompson",
    "Brittany Hood",
    "Kelly Bell",
    "Jack Callahan",
    "Thomas Wilson",
    "Shelby Merritt",
    "Jerry Rogers",
    "Carol Thomas",
    "Allison Garner",
    "Brian Stewart",
    "Amy Bates",
    "Jay Martin",
    "Wayne Watson",
    "Alan Harrington",
    "Isaiah Crane",
    "Kimberly Ramsey",
    "Nichole King",
    "Jennifer Black",
    "Brittany Alexander",
    "Robert Foster",
    "Michael Ross",
    "Ivan Allen",
    "Pamela Miller",
    "Ryan Marshall",
    "Bethany Sanchez",
    "Jill Davis",
    "Adam Kline",
    "Jesse Stein",
    "George Owens",
    "Travis Gray",
    "Denise Goodwin",
    "Tricia Williams",
    "Terry Williams",
    "Alicia Turner",
    "Kara Perez"
    ]

 users.forEach(names => {
      it(`Enters ${names}`, () => {
        cy.get('input[class="input"]').type(names)
        cy.contains('Send')
        // cy.contains('See you in')
      });
  });
})