describe('Form Submission 2', () => {
  beforeEach(() => {
    cy.visit('https://visitspandau.club/')
  })

  const users = [     
    "Samantha Frost",
    "Daniel Schneider",
    "Clarence Wood",
    "Larry Martinez",
    "Amber King",
    "Victoria Roman",
    "Leslie Benitez",
    "Derek Patel",
    "Hannah Jones",
    "Scott Jimenez",
    "Jonathon Peterson",
    "Andrew Bird",
    "Olivia Rios",
    "Erin Smith",
    "Nicholas Navarro",
    "Danielle Thompson",
    "Elizabeth Wolfe",
    "Virginia Reed",
    "Katie Reyes",
    "Angela Woods",
    "Brandi Spears",
    "Chloe Duncan",
    "Patrick Osborne",
    "Susan Guerrero",
    "Daniel Fisher",
    "Jeffrey Long",
    "Joshua Salas",
    "Michael Mullins",
    "Tamara Robbins",
    "Dean Ramirez",
    "Amber Hoover",
    "Michael Livingston",
    "Heidi Turner",
    "Michael Miller",
    "Timothy West",
    "Robin Price",
    "Cheryl Flores",
    "Raymond Day",
    "Rachel Simon",
    "Diana Horton",
    "Brandon Thompson",
    "William Clark",
    "Stephanie Morrow",
    "Timothy Moore",
    "Ashley Barnes",
    "Karen Wilson",
    "Nathaniel Baldwin",
    "Megan Wilson",
    "Christy Roberson",
    "Jane Peters",
    "Terry Dennis",
    "Abigail Ingram",
    "Jeremy Booth",
    "Justin Chavez",
    "Diane Walker",
    "Nancy Freeman",
    "Susan Lee",
    "Tracey Butler",
    "Brian Vaughn",
    "Dillon Tucker",
    "James Garrett",
    "Shari Carroll",
    "Theresa Moreno",
    "Kristen Washington",
    "Robert Lane",
    "John Benitez DDS",
    "Zachary Dennis",
    "Jasmine Lopez",
    "Alicia Flowers",
    "Jamie Neal",
    "Danielle Banks",
    "Logan Woods",
    "John Lang",
    "Alan Chen",
    "Diana Beck",
    "Gregory Jackson",
    "Blake Munoz",
    "Jeremy Lewis",
    "Robin White",
    "Luis Jones",
    "Kristina Oneal",
    "Kimberly Davidson",
    "Mark Burns",
    "Kelly Byrd",
    "Eric Johnson",
    "Whitney Price",
    "Patricia Webb",
    "Ryan Novak",
    "Joseph Boyd",
    "Brad Ford",
    "Steven Simpson",
    "Jordan Vega",
    "Joel Andrews",
    "Katherine Alexander",
    "David Taylor",
    "James Roth",
    "Christian Mayer",
    "Jessica Mason",
    "Danielle Wheeler"
    ]

 users.forEach(names => {
      it(`Enters ${names}`, () => {
        cy.get('input[class="input"]').type(names)
        cy.contains('Send')
        // cy.contains('See you in')
      });
  });
})