describe('Form Submission 4', () => {
  beforeEach(() => {
    cy.visit('https://visitspandau.club/')
  })

  const users = [
      "Jacob Davis",
      "Michael Duarte",
      "Cynthia Smith",
      "Eddie Long",
      "Megan Grant",
      "Michael Simpson",
      "Aaron Jensen",
      "Melissa Woodward",
      "Cynthia Townsend DDS",
      "Sandra Hayes",
      "Eric Weeks",
      "Shaun Hicks",
      "Nicholas Lee",
      "Pamela Riggs",
      "Annette Simpson",
      "Daniel Kelly",
      "Eric Mendoza",
      "Erika Lyons",
      "Michelle Wheeler",
      "Cheryl Henry",
      "Dennis Kline",
      "Kristen Yoder",
      "Leslie Perez",
      "Rhonda Brown",
      "Cheryl Sandoval",
      "John Contreras",
      "Stephen Thomas",
      "Kenneth Warren",
      "Natasha Wallace",
      "Kevin Leon",
      "Melanie Armstrong",
      "Pamela Barnett",
      "James Matthews",
      "Michele Diaz",
      "Taylor Shah",
      "Christina Nguyen",
      "Karla Soto",
      "David Howard",
      "Lisa Friedman",
      "Douglas Phillips",
      "David Robinson",
      "Michele Rojas",
      "Jacob Browning",
      "Curtis Morgan",
      "Anthony Jordan",
      "Kimberly Cohen",
      "Jeanette Barnett",
      "Misty Obrien",
      "Courtney Walsh",
      "Donald Moore",
      "Allison Dominguez",
      "James Morrison",
      "Jerry Gallagher",
      "Kelly Washington",
      "Mr. Jeremy Arellano MD",
      "Shannon Martinez",
      "Daniel Clark",
      "Mrs. Barbara Davis",
      "Robert Kim",
      "Julie Singleton",
      "Andrew Houston",
      "Kyle Mckenzie",
      "Joanne Alvarez",
      "Donald Robinson",
      "Isaac Garcia",
      "Mark Chapman",
      "Mary Koch",
      "Daniel Page PhD",
      "Joshua Benson",
      "Jenna Parks",
      "Jeremiah Russell",
      "Heather Bowers",
      "Jeffrey Hall",
      "Brandon Smith",
      "Madeline Torres",
      "Michelle Johnson",
      "Robert Johnson",
      "Heather Schmitt",
      "Peggy Henry",
      "Randy Mcgee",
      "Natalie Richard",
      "Veronica Zimmerman",
      "Laurie Byrd",
      "Krista Reed",
      "Barry Mclean",
      "Richard Evans",
      "Brittany Hall",
      "Kevin Callahan",
      "Courtney Green",
      "Anthony Werner",
      "Angelica Wilcox",
      "Karen Warren",
      "Angela Wilcox",
      "Sue Snyder",
      "Zachary Benitez",
      "Nicholas Arias",
      "Courtney Davis",
      "Thomas Rocha",
      "Rebecca Gates"
    ]

 users.forEach(names => {
      it(`Enters ${names}`, () => {
        cy.get('input[class="input"]').type(names)
        cy.contains('Send')
        // cy.contains('See you in')
      });
  });
})