describe('Form Submission 5', () => {
  beforeEach(() => {
    cy.visit('https://visitspandau.club/')
  })

  const users = [
      "Alexander Porter",
      "Steve Browning",
      "Morgan Hawkins",
      "Daniel Smith",
      "Kenneth Fisher",
      "Gina Swanson",
      "Donna Peterson",
      "Michelle Baker",
      "Amy Davila",
      "Joseph Oconnell",
      "Kendra West",
      "Gabriel Anderson",
      "Melissa Love DVM",
      "Jason Long",
      "Mrs. Jessica Luna",
      "Christopher Williams",
      "Ivan Robbins",
      "Dennis Fowler",
      "Michelle Hernandez",
      "Scott Hall",
      "Stephen Ross",
      "Zachary Wilson",
      "April Brennan",
      "Taylor Chambers",
      "Jennifer Scott",
      "Joseph Velez",
      "Leslie Guerra",
      "Alison Banks",
      "Jaime Mckenzie",
      "Erika Martin",
      "Ryan Griffin",
      "David Smith",
      "Jennifer Gomez",
      "Andrew Lopez",
      "Carrie Robinson",
      "Erin Stevenson",
      "Mark Miller",
      "Michelle Perkins",
      "Suzanne Brooks",
      "Taylor Johnson",
      "Julie House",
      "Jaime Joseph",
      "Linda Santos",
      "Levi Prince",
      "Michael Ellis",
      "Mrs. Dana Garcia",
      "Kimberly Gonzalez",
      "Brenda Murillo",
      "Michael Love",
      "Angela Greene",
      "David Bender",
      "Heather Vargas",
      "Brandon Walker",
      "Christina Payne",
      "Alexandra Wilson",
      "Carol Miller",
      "Monique Graham",
      "Matthew Diaz",
      "Joshua Klein",
      "Jennifer Joseph",
      "Leslie Tran",
      "Dr. Kevin Arnold",
      "Raymond Thompson",
      "Michael Jones",
      "Ian Woodard",
      "Joshua Moore",
      "Christopher Simpson",
      "Natasha Dawson",
      "Leslie Knox",
      "Tracy Benton",
      "Shawn Bailey",
      "John Taylor",
      "Melody Campbell",
      "Robert Anderson",
      "Victoria Sanchez",
      "Christopher Crawford",
      "Emily Lopez",
      "Audrey Young",
      "Alexander Armstrong",
      "Katherine Smith",
      "Jeffery Anderson",
      "Brandy Fuller",
      "Ashley Farley",
      "Kristy Lara",
      "Austin Wood",
      "Nicole Patterson",
      "Kimberly Trujillo",
      "Mary Leonard",
      "Joel Bailey",
      "Priscilla Travis",
      "Michael Kirby",
      "Beverly Roberts",
      "Crystal Shelton",
      "Garrett Foster",
      "Andrew Mckinney",
      "Sydney Hernandez",
      "Shawn Moyer",
      "Blake Graves",
      "Katrina Holmes",
      "Mandy Pittman"
    ]

 users.forEach(names => {
      it(`Enters ${names}`, () => {
        cy.get('input[class="input"]').type(names)
        cy.contains('Send')
        // cy.contains('See you in')
      });
  });
})