describe('Form Submission 8', () => {
  beforeEach(() => {
    cy.visit('https://visitspandau.club/')
  })

  const users = [
    "Martha Diaz",
    "David Lambert",
    "Joshua Murphy",
    "Donna Sandoval",
    "Lauren Thomas",
    "Cynthia Ball",
    "Amber Walsh",
    "Casey Moran",
    "Heidi Powers",
    "Miguel Floyd",
    "Haley Vaughn",
    "Julie Ross",
    "Steven Woods",
    "Nicholas Walters",
    "Joseph Hill",
    "Judy Taylor",
    "Nicole Carpenter",
    "Samuel Gutierrez",
    "Melissa Oneill",
    "Derrick Vaughn",
    "Caitlin Wang",
    "Angela Davis",
    "Donald Smith",
    "Cindy Simpson",
    "Michael Knight",
    "Aaron Wilson",
    "Krystal Armstrong",
    "Michael Ryan",
    "Dana Hodges",
    "Bruce Moran",
    "Chelsea Martinez",
    "Taylor Miller",
    "Stephanie Wise",
    "Mrs. Linda Harrell MD",
    "David Hicks",
    "Ryan Moore",
    "Nicholas Stout",
    "Dale Bennett",
    "Christopher Watson",
    "Matthew Wilson",
    "Melissa Edwards",
    "Carlos Curry",
    "Brian Mitchell",
    "Christy Shah",
    "Samuel Romero",
    "Dr. Alicia Farrell",
    "Rebecca Smith",
    "Jamie Johnson",
    "Brandi Dunn",
    "Donald Howe",
    "Laura Martinez",
    "Jacob Schneider",
    "Gail Carrillo",
    "Shelby Williams",
    "Michael Park",
    "Phyllis Hall",
    "Linda Hammond",
    "Antonio Newman",
    "Nicholas Carroll",
    "Jeremy Lewis",
    "Michael Jackson",
    "George Hurst",
    "Sharon Nicholson",
    "Robert Wilson",
    "Lauren Brooks",
    "Donald Lyons",
    "Sean Davis",
    "Samantha Schroeder",
    "Andre Walker",
    "Willie Haney",
    "Daniel Burns",
    "Mark Carney",
    "Leslie Lopez",
    "Sherri Smith",
    "Cassandra Burnett",
    "Nicholas Ross",
    "Brian Williams",
    "Matthew Lopez",
    "Tamara Greer",
    "Christopher Bender",
    "Mrs. Melanie Miller",
    "Jennifer Howell",
    "Tara Page",
    "James Golden",
    "Daniel Carr",
    "Richard Smith",
    "Lindsey Olson",
    "Jon Gross",
    "Heather Long",
    "Rachel Bennett",
    "Andrea Walker",
    "Julie Hartman",
    "Dale Irwin",
    "John Pittman",
    "Christian Allen",
    "Barbara Khan",
    "Carl Brennan",
    "Matthew Villegas",
    "Adam Dixon",
    "Andrea Bell"
    ]

 users.forEach(names => {
      it(`Enters ${names}`, () => {
        cy.get('input[class="input"]').type(names)
        cy.contains('Send')
        // cy.contains('See you in')
      });
  });
})