name: Cypress Testss

on:
  schedule:
    - cron: "* * * * *"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install