name: Cypress Tests

on:
  schedule:
    - cron: '* * 1,3,4,8,10,15,19,22,26 * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install