name: Cypress Tests - Parallel

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
        container: cypress/browsers:node12.14.1-chrome85-ff81
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}