name: Cypress Tests - Parallel

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          parallel: true
          command: cypress run --record --parallel --key 3679b9ed-ee3d-46b6-8ec4-7de34e62ffb0
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}