name: Cypress Tests - Parallel

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '5 4 1,4,7,12,15,17,21,25,28 * *'
  #   # At 04:05 on day-of-month 1, 4, 7, 14, 15, 17, 21, 25, and 28.
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          parallel: true
          command: npm run cypress:record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}